services:
  # Lancer le frontend
  frontend:
    build: ./frontend
    # environment:
    #   VITE_APP_BACKEND_API_URL: http://127.0.0.1:8000
    # DÃ©claration des variables d'environnement du container
    ports:
      - 5173:5173

  api:
    build: ./backend
    ports:
      - 3000:3000