services:
  # Lancer le frontend
  mongo-db:
    image: mongo
    container_name: mongo-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27018:27017"
    
  
  frontend:
    build: ./frontend
    environment:
      VITE_APP_BACKEND_API_URL: http://127.0.0.1:3000
    ports:
      - 5173:5173

  api:
    build: ./backend
    depends_on:
      - mongo-db
    environment:
      MONGODB_URI: mongodb://user:password@mongo-db:27017
      MONGODB_DATABASE: ts_park
      BCRYPT_SALT: SALT
      JWT_SECRET: SECRET
    ports:
      - 3000:3000 